version: '3.4'

services:
  humanrelations.api:
    environment:
      - EventBus__RabbitMQ__Host=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Data Source=sqldata;Database=KWops.HumanRelations;UserID=sa;Password=Pass@word
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sqldata:
    environment:
    - SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    ports:
    - "1433:1433"
    volumes:
    - kwops-sqldata:/var/opt/mssql

  devops.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ConnectionString=DataSource=sqldata;Database=KWops.DevOps;User Id=sa;Password=Pass@word
        - EventBus__RabbitMQ__Host=rabbitmq
        - Urls__IdentityUrl=http://identity.ui
    ports:
        - "6000:80"
        - "6001:443"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  rabbitmq:
    ports:
        - "15672:15672"
        - "5672:5672"
  
  identity.ui:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ConnectionString=DataSource=sqldata;Database=KWops.HumanRelations;UserId=sa;Password=Pass@word
    ports:
        - "9000:80"
        - "9001:443"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  kwops-sqldata:
    external: false

    
    